style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/spotinst/terraform-spotinst-elastigroup-aws
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
